### ISSUE TITLE
.NET version

### ISSUE THREAD

**Issue by dariozanelli** [TimothyKhouri/WkHtmlToXDotNet#2]
Hi,
I am trying to enclose the dll in my project .NET 4.5 but I am getting an error since it has been compiled for .NET 4.5.1.
Is it possible to get the dll for the previous version of the framework?

Thanks and regards,
Dario Zanelli

**Comment by TimothyKhouri** [comment]
Really, we should be moving up to 4.5.2 - since that's what's going to be supported going forward... but I'll attach the DLL compiled in 4.5 for ya :)

[WkHtmlToXDotNet.dll compiled in .NET 4.5](https://github.com/TimothyKhouri/WkHtmlToXDotNet/releases/download/v0.1.1/WkHtmlToXDotNet.dll)

**Comment by dariozanelli** [comment]
Thanks a lot!

**Comment by dariozanelli** [comment]
I have another question: is it possible to create bookmarks in the created pdf, in order to use them as index of the document?
Cheers,
Dario

**Comment by TimothyKhouri** [comment]
Great question - I don't really know the answer to that :)

The PDF generation tool is actually built by Google I think - I just
wrapped it for .NET, so if they support that (probably they do), then this
would as well.

**Comment by dariozanelli** [comment]
The dll is not strongly signed. I tried disassembling it but it didn't work. I have to deploy it in the global Assembly Cache. Is it possible to get it signed with a key? How can I send you the key?
