### ISSUE TITLE
UTF 8

### ISSUE THREAD

**Issue by angelcalvasp** [TimothyKhouri/WkHtmlToXDotNet#3]
Hello there I am using the tag

<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

in my html to change the charset but when the pdf Is rendered characters with tilde show up as question marks am I missing something? is there any other way to make this work?

**Comment by TimothyKhouri** [comment]
Honestly I have no clue... I didn't write the HtmlToPDF part - that's Google's library. All I've done is wrapped it in c#. I would post your question on StackOverflow for that library in particular if I were you.
