### ISSUE TITLE
Error Could not load file or assembly 

### ISSUE THREAD

**Issue by makwanaa** [TimothyKhouri/WkHtmlToXDotNet#4]
Hi
I am using WkHtmlToXDotNet.DLL in ASP.NET but I am getting following error

Could not load file or assembly 'WkHtmlToXDotNet.DLL' or one of its dependencies. The specified module could not be found.

I have wkhtmltox.dll in my bin folder.

**Comment by CSADn** [comment]
Same here...

**Comment by TimothyKhouri** [comment]
This project isn't really supported anymore... Google hasn't done much to the underlying DLL, and there are some terrible design flaws around multi-threading.

That being said, I've seen generic .NET errors like this before, and you will likely have to check the Fusion logs to see more details.

Steps I would take - 1) try to use this project in a console app, 2) switch all to x86 mode and see if that helps, 3) check the Fusion log etc.

It could (unfortunately) be a hundred different issues causing that generic error message.
